services:
  - type: web
    name: minilinkedin-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: minilinkedin-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
        length: 64
